FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    pandas==2.2.3 \
    numpy==1.26.4 \
    scikit-learn==1.5.2 \
    xgboost==2.1.3 \
    streamlit==1.41.1 \
    joblib==1.4.2

COPY src/ src/
COPY models/ models/

EXPOSE 8503

CMD ["streamlit", "run", "src/app/streamlit_app.py", \
     "--server.port=8503", \
     "--server.address=0.0.0.0", \
     "--server.baseUrlPath=/pred-maintenance-ui", \
     "--server.headless=true"]
